on:
  push:
    branches:
      - main
  pull_request:

name: docs

permissions:
  pull-requests: write
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "nvim-java-core"
          dedupsubheadings: false
          version: "Neovim >= 0.9.4"
          demojify: true
          treesitter: true
          shiftheadinglevelby: 0
          docmappingprojectname: false
          incrementheadinglevelby: 1

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: "main"
